const items = [
  {
    id : '001',
     item_image:'Images/newOffer1.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '002',
     item_image:'Images/newOffer2.jpg',
  rating :{
    stars : 5.5,
    noOfReviews: 1300,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  {id : '003',
     item_image:'Images/newOffer3.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '004',
     item_image:'Images/newOffer4.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '005',
     item_image:'Images/newOffer5.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '006',
     item_image:'Images/newOffer6.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '007',
     item_image:'Images/newOffer7.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  },
  { id : '008',
     item_image:'Images/newOffer8.jpg',
  rating :{
    stars : 4.5,
    noOfReviews: 1400,
  },company_name :'Carton London',
  item_name : 'Rhodium-Plated CZ floral Studs',
  current_price : 'RS 606',
  original_price :'RS 1045',
  discount : 42,
  }
]